---
- hosts: "{{ hosts | default ('localhost')}}"
  connection: local
  gather_facts: false

    
  # vars:
  #   optional_vars_file: "{{ lookup('first_found', 'vars.yml', errors='ignore') }}"
    
    
  roles:
    - createvars