---
- name: Set variables
  set_fact:
    #optional_vars_secrets: "{{ lookup('env', 'SECRETS')| to_json}}"
    optional_vars_secrets: "{{ lookup('file', 'secrets.json', errors='ignore')}}"
    optional_vars_kubernetes: "{{ lookup('file', 'kubernetes.json', errors='ignore')}}"

- name: Create secrets vars
  debug:
    msg: "'{{ lookup('env', 'SECRETS') }}' is the HOME environment variable."

- name: Create secrets vars
  debug:
    msg: "'{{ optional_vars_secrets }}' is the from SET environment variable."

- name: Create secret variables file 
  template:
    src: secret-vars-file.j2
    dest: "secret-vars-file.yaml"
  when: optional_vars_secrets != ""

- name: Create kubernetes variables file 
  template:
    src: kubernetes-vars-file.j2
    dest: "kubernetes-vars-file.yaml"
  when: optional_vars_kubernetes != ""