---
- name: Set variables
  set_fact:
    container_tag: "{{ lookup('env', 'TAG')}}"
    optional_vars_kubernetes: "{{ lookup('env', 'SECRETS_CONTEXT', errors='ignore')}}"

    #optional_vars_secrets: "{{ lookup('file', 'secrets.json', errors='ignore')}}"
    #optional_vars_kubernetes: "{{ lookup('file', 'kubernetes.json', errors='ignore')}}"


# cria arquivos com secrets k8s
- name: Create secret variables file 
  template:
    src: secrets-vars-file.j2
    dest: secrets-vars-file.yaml
  when: optional_vars_kubernetes != ""
# cria arquivos de variaveis k8s
- name: Create kubernetes variables file 
  template:
    src: kubernetes-vars-file.j2
    dest: kubernetes-vars-file.yaml
  when: optional_vars_kubernetes != ""



